
import { Game, User, Review } from './types';

export const GAMES: Game[] = [
  {
    id: 'cybernetic-horizon',
    title: 'Cybernetic Horizon',
    developer: 'FutureSoft',
    publisher: 'FutureSoft',
    releaseDate: 'TBA',
    price: 'Pre-order',
    description: 'Experience the next generation of open-world adventure.',
    longDescription: "Cybernetic Horizon throws you into the neon-drenched streets of Neo-Kyoto in 2242, a sprawling metropolis where mega-corporations rule and cybernetic enhancements are the key to survival. As a freelance netrunner haunted by a fractured past, you'll navigate a world of corporate espionage, rogue AIs, and underground revolutions. Your choices matter, shaping the story and the fate of the city itself.",
    genres: ['Open World', 'RPG', 'Sci-Fi'],
    platforms: ['desktop_windows', 'laptop_mac'],
    rating: 4.9,
    reviewCount: 15230,
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjPdVB3e7A5EgBz5uRzRdhFXOaInZyBMGekAzr02KPmol41jI1KGhkK-btLddQXfrJZ31HhNTlb0wdN-8I_WFaeL4f_twl5wNA97c65NJHNIf-lIU-OWaHvI7M5ZpPJXk5AQ7RGgFWAzwOpJQyOb53dOrN-lLfu9UgUEQ26rHsVA0rxewRGoF7oDU5oQgWN-4foPu2uQv6rdDxbeH_L8Pp3Vi7zi-AGJ-Hcqfut7hT46e-A1Nn8yCJHvotLYuyeic_h94AhhPu2Og',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3pgunxVLUo9pnz0lTwR9XydNtwAk3wdmStepojWck1rx8pB12kz4UlCofnSKOo_K60ItynazIbLZjAUPIIVlMqtcdkMW4D-liKvSHaSTPNwDvk4hXLtxiWaLW_Y0yI1Z88jAT21sphoX9UBlNBQ_hFmK_cOvlCdqOIY_YQ3O8hFcUc82JEXa1N_xUJ6aNRQzTQ41KQ0IH5d0RcFtiuOpgyJbj23myxLKdn-TOQ3iwwEd1de_ILkTIUQog1j4VXkvOZl-xkcLneWQ',
    gallery: [
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ1YLpQmI5hDU9Vktj0QpEeP4zK9rwPw4at41925oHn0LqXRyS2Jzw3iWChFoJHdl2CbzfMbiCrRxWDyRmMHosA8uJm_oIPsCqfugEa8adMl7uLwexQevTgloayfsfF9mbGSM30tJYbV4870KM6E0kte5oLFLsuIhTYk6qS7iPas8NfJrOWq3jtA40Lkay51wXeEMzzpZhd_3Tb0jWppMz6Rh-ubwX2RrKww8urNCF1D1nSI7B0ln6mzo7a7aC1OYVLhbLyeSiVJE',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuB_JpnWSf0nqBSmBBGVAggnGWcf2FeqWR_AJj4VVDTqww3r7a96HGwKbTw0xNJqXePJM7l5oxxSsnQ51rg_RvCBdS25Ugtq_BArluUxlCGa3dlfwmbI251MkN8m6LSYgoruh5gF_7HokNj9-cI7mk2J0p-KP3ZgE2TaXpLsLfoAQkIb1KGyYTH1SQb-WmxSb9Mvi2O2lgXT1ZbiFkaKbdR8EbMxoPoKy_t8wl-0-1qdPue7RGuku8VAi00g-IYE5qf4fQooJ1I2OYU',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuDPcU9l-G4hJM_OsceLiBfaM_tyDYbCYS5CacuTmng38BR7lhS8eJI5LRE10JIyFqhpz9laNlt6CwnQVjZiipepyftO3GQ2gxfRqWUXyIukwcsqVz7HleYajkXF1DO42MEUX_H1vg9YojEGY6FIGk5zDOkXQlMob_Vmp54DZWjFUERnQn3Q2QYsMOElXtrSKTATEe17EcBSR2su0EhxlGz5ZTrYuUTDzUHrbfD1KyCiCOhfu1e9Reg_1XjCHTLIh2Nu8lOKyLPPq5A',
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBK3H_i2zPa_ErNNu1T-y4H69NgY3_zBaeNRVE6DUYhJUaboTaVIybMst8b_oItj3WAnGjSXRFSyqhx0i75d3KLeKI0S9SSszB08zHXeRGH9IDTwgKSoDkNm7TKJuXTkkTH70HJ_BGY-4nQuscwDSYExXPwWLffHBvKLy94JRGyftigUc8oU9IjSXmtAArJr9608vsjwDOxL6PL-U_fLm7K7NPal4714FJv6XIbVxV0zWLzz_8GKWB5nVaZeA3pp-CEAPpObJ4Zgmk',
    ],
    trailerUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    isFeatured: true,
  },
  {
    id: 'stellar-odyssey',
    title: 'Stellar Odyssey',
    developer: 'Cosmic Interactive',
    publisher: 'Galaxy Studios',
    releaseDate: 'Mar 15, 2023',
    price: 'Free to Play',
    description: 'A space-faring adventure across galaxies.',
    longDescription: 'Embark on an epic journey across the stars in Stellar Odyssey. Pilot your customizable starship, explore unknown planets, trade with alien species, and engage in thrilling space combat. The galaxy is vast and full of secrets waiting to be discovered.',
    genres: ['Space Sim', 'Adventure', 'RPG'],
    platforms: ['desktop_windows'],
    rating: 4.5,
    reviewCount: 8540,
    heroImage: 'https://picsum.photos/seed/stellar-odyssey-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3pgunxVLUo9pnz0lTwR9XydNtwAk3wdmStepojWck1rx8pB12kz4UlCofnSKOo_K60ItynazIbLZjAUPIIVlMqtcdkMW4D-liKvSHaSTPNwDvk4hXLtxiWaLW_Y0yI1Z88jAT21sphoX9UBlNBQ_hFmK_cOvlCdqOIY_YQ3O8hFcUc82JEXa1N_xUJ6aNRQzTQ41KQ0IH5d0RcFtiuOpgyJbj23myxLKdn-TOQ3iwwEd1de_ILkTIUQog1j4VXkvOZl-xkcLneWQ',
    gallery: ['https://picsum.photos/seed/stellar-odyssey-1/1920/1080', 'https://picsum.photos/seed/stellar-odyssey-2/1920/1080'],
    isFeatured: true,
  },
  {
    id: 'forgotten-realms',
    title: 'Forgotten Realms',
    developer: 'Old School Studios',
    publisher: 'Fantasy Interactive',
    releaseDate: 'Jun 22, 2023',
    price: '$49.99',
    description: 'Explore dark dungeons and find epic loot.',
    longDescription: 'Venture into the Forgotten Realms, a land of magic, monsters, and myth. Choose your path as a noble knight, a cunning rogue, or a powerful wizard. Uncover ancient artifacts, defeat legendary beasts, and forge your own legend in this classic fantasy RPG.',
    genres: ['RPG', 'Fantasy', 'Adventure'],
    platforms: ['desktop_windows', 'laptop_mac'],
    rating: 4.8,
    reviewCount: 11200,
    heroImage: 'https://picsum.photos/seed/forgotten-realms-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsumeJC-b62dIBVQ4GKtZhY7YQrpfMj-t5TzTEcfm7eNvFfWb7588NcErstVfdXvJt0wonyvIvRgwkoxsDVcYqDgP_IG4Hgqg_dcdykB25TlUgPcCno8a9XCXTYMR0Ngh6mrIcdCHiku2fQB4Geyv3YLtmGlU43HXg4nJj9hNj6A1R8Q8HP9F_qu7JSM_-_P0AbqPeXNJCZw4DEYTop1xLg87E_CHLzovMNtSFD0NhDwiETgzayBFGjterW_VvWlmWsCz_msgOabc',
    gallery: ['https://picsum.photos/seed/forgotten-realms-1/1920/1080', 'https://picsum.photos/seed/forgotten-realms-2/1920/1080'],
    isFeatured: true,
  },
  {
    id: 'speed-demons-4',
    title: 'Speed Demons 4',
    developer: 'Velocity Games',
    publisher: 'Velocity Games',
    releaseDate: 'Sep 01, 2023',
    price: '$59.99',
    description: 'High-octane racing action.',
    longDescription: 'Get behind the wheel in the most realistic racing simulator yet. Speed Demons 4 features stunning graphics, precise physics, and a wide variety of cars and tracks. Compete in a thrilling career mode or challenge players online to prove you are the fastest.',
    genres: ['Racing', 'Simulation', 'Sports'],
    platforms: ['desktop_windows'],
    rating: 4.7,
    reviewCount: 9300,
    heroImage: 'https://picsum.photos/seed/speed-demons-4-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAslr8sUnZopuiav_w1Xrr3PX3gwFk4QKxHgrR1h5rQsEUdbKUrEKvdTtWKAQLjgMMqmWu9yIR4d0NJznlIWdTMVzJvroI4wsq0Fw-2-PtEr7ghDLGJdGLf-vf8idr0mvDk7dbMIeIOuRvBGTJt1sZysPazfgM88zJKNKVYnqT4OmBLxBJROr1biH08SgpThwRTYR9efT3PPqIsZIdPi7Zzrp0C0okN90urULNBSp3P5zXs22VOyTxJNGEz4yPT6PpJHCAXJskY5LU',
    gallery: ['https://picsum.photos/seed/speed-demons-4-1/1920/1080', 'https://picsum.photos/seed/speed-demons-4-2/1920/1080'],
    isFeatured: true,
  },
   {
    id: 'cyberpunk-odyssey',
    title: 'Cyberpunk Odyssey',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    releaseDate: 'Oct 10, 2024',
    price: '$59.99',
    description: 'Navigate a world of corporate espionage, rogue AIs, and underground revolutions.',
    longDescription: "Cyberpunk Odyssey throws you into the neon-drenched streets of Neo-Kyoto in 2242, a sprawling metropolis where mega-corporations rule and cybernetic enhancements are the key to survival. As a freelance netrunner haunted by a fractured past, you'll navigate a world of corporate espionage, rogue AIs, and underground revolutions. Your choices matter, shaping the story and the fate of the city itself. Featuring a vast, seamless open world, deep character customization with unique cybernetic abilities, and a branching narrative with multiple endings, Cyberpunk Odyssey offers unparalleled freedom. Wield high-tech weaponry, hack into corporate mainframes, and forge alliances in a city that never sleeps. The future is yours to define.",
    genres: ['Action', 'RPG', 'Open World'],
    platforms: ['desktop_windows', 'laptop_mac'],
    rating: 4.8,
    reviewCount: 12450,
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaKC3thZjMLVD4YW1-WFHTM0UIUaPFUXELBX7UtugQRi4kavh5NsZSvDxDnLiOapoFas8xS623h_SVgqvhk5kUr1szREnpIjLSjj-n2yHyfLrRvArdfsh1hImasKClZcj1IpD__JO7KeGkklFuAzPCw6snhfSK0S6tbkwOgyv1b0DFP9tIuynkn-6cJZ8YhZFtZZHWWUTKU3WCzkeGY9_KtRv0oLc3beBK9Zfq0EHyUbN5t_2glnIw-dazT1QjElMw-3DMQ6GxrSU',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcYk4TQD5lZLwIyoqarls5UGFt1ZSOm7TpuAXZcJGPBskFoA_dHctjwK8Ouht8L8nqHi_w5jwhvEnao_Y0lO77-13sI1yjTkvbrFCmRHDpTkXXVaaCF3uSAwBZugZ4kjEg7vL_OQa9EeZOX4r4ktKtqkBQ-E0Vt3DZAnjpXfDr23jIUxC8kmuHZ7Cpj_Ntf6H8PTIb7pCE5PyCs8lTbemcxklA84EfXSKEmjswDSKefwR9Eil3BB7_BQLFerFfZV_zlLS4GoeIKVg',
    gallery: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBJ1YLpQmI5hDU9Vktj0QpEeP4zK9rwPw4at41925oHn0LqXRyS2Jzw3iWChFoJHdl2CbzfMbiCrRxWDyRmMHosA8uJm_oIPsCqfugEa8adMl7uLwexQevTgloayfsfF9mbGSM30tJYbV4870KM6E0kte5oLFLsuIhTYk6qS7iPas8NfJrOWq3jtA40Lkay51wXeEMzzpZhd_3Tb0jWppMz6Rh-ubwX2RrKww8urNCF1D1nSI7B0ln6mzo7a7aC1OYVLhbLyeSiVJE',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB_JpnWSf0nqBSmBBGVAggnGWcf2FeqWR_AJj4VVDTqww3r7a96HGwKbTw0xNJqXePJM7l5oxxSsnQ51rg_RvCBdS25Ugtq_BArluUxlCGa3dlfwmbI251MkN8m6LSYgoruh5gF_7HokNj9-cI7mk2J0p-KP3ZgE2TaXpLsLfoAQkIb1KGyYTH1SQb-WmxSb9Mvi2O2lgXT1ZbiFkaKbdR8EbMxoPoKy_t8wl-0-1qdPue7RGuku8VAi00g-IYE5qf4fQooJ1I2OYU',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDPcU9l-G4hJM_OsceLiBfaM_tyDYbCYS5CacuTmng38BR7lhS8eJI5LRE10JIyFqhpz9laNlt6CwnQVjZiipepyftO3GQ2gxfRqWUXyIukwcsqVz7HleYajkXF1DO42MEUX_H1vg9YojEGY6FIGk5zDOkXQlMob_Vmp54DZWjFUERnQn3Q2QYsMOElXtrSKTATEe17EcBSR2su0EhxlGz5ZTrYuUTDzUHrbfD1KyCiCOhfu1e9Reg_1XjCHTLIh2Nu8lOKyLPPq5A',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBK3H_i2zPa_ErNNu1T-y4H69NgY3_zBaeNRVE6DUYhJUaboTaVIybMst8b_oItj3WAnGjSXRFSyqhx0i75d3KLeKI0S9SSszB08zHXeRGH9IDTwgKSoDkNm7TKJuXTkkTH70HJ_BGY-4nQuscwDSYExXPwWLffHBvKLy94JRGyftigUc8oU9IjSXmtAArJr9608vsjwDOxL6PL-U_fLm7K7NPal4714FJv6XIbVxV0zWLzz_8GKWB5nVaZeA3pp-CEAPpObJ4Zgmk',
    ],
  },
  {
    id: 'echoes-of-war',
    title: 'Echoes of War',
    developer: 'BattleCry Studios',
    publisher: 'Warfront Ent.',
    releaseDate: 'Oct 05, 2023',
    price: '$69.99',
    description: 'A tactical FPS set in a gritty, modern conflict.',
    longDescription: 'Experience the intensity of modern warfare in Echoes of War. This tactical first-person shooter emphasizes teamwork, strategy, and realistic combat mechanics. Join a squad, choose your role, and fight for victory in large-scale multiplayer battles.',
    genres: ['FPS', 'Tactical', 'Multiplayer'],
    platforms: ['desktop_windows'],
    rating: 4.6,
    reviewCount: 7800,
    heroImage: 'https://picsum.photos/seed/echoes-of-war-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByQXOXYC08Y5Uzf-7BxpFF31ZeeBDoXRYX1fbmad93QsPU33Kk-GilSqLVXaDpINgxO-3IxehxVfBRN8BCBoRZ4LbOvqAqjZokCm1b8b2d33Un_HgIYfPkZfmvAgxOEMw4cX0Zd-NuvLpZAMESV1ojVCLUkWRgdL_TMJ0TM0gJZfhGx-9JXLtf-ZtrFmn1kfjFX9IQhovOh0GFRyfIEpbI09W9x9pomhnnHTJcFoWW79qEk33O52LOw7pQnB83Qt4IK85E6vEveIg',
    gallery: ['https://picsum.photos/seed/echoes-of-war-1/1920/1080', 'https://picsum.photos/seed/echoes-of-war-2/1920/1080'],
    isTrending: true,
  },
  {
    id: 'neon-drift',
    title: 'Neon Drift',
    developer: 'SynthWave Games',
    publisher: 'RetroFuture',
    releaseDate: 'Nov 11, 2023',
    price: '$39.99',
    description: 'Arcade racing with a retro-futuristic aesthetic.',
    longDescription: 'Drift through neon-soaked cityscapes in this stylish arcade racer. Master the art of the drift to earn boost and leave your opponents in the dust. With a killer synthwave soundtrack and vibrant visuals, Neon Drift is a feast for the senses.',
    genres: ['Racing', 'Arcade', 'Indie'],
    platforms: ['desktop_windows', 'laptop_mac'],
    rating: 4.8,
    reviewCount: 6500,
    heroImage: 'https://picsum.photos/seed/neon-drift-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC50luf9A3SlObxgyE2aTkYEa-Vftm1-QckAGN69_fb7i5-B59nJTnbQDZC2Ti70RPUQEI3XNicEPjSUDoVlBQy5hsD93uzC1H2NLuupHVBmpEKb0z0OYx_AiRPTNMvqBMjnTv93U0akBlSuaApSL7vLSZamOHsyOAcT1bLLTFKXHYzK_7Gapj5taJlctobAiauxGetKNYjcB6z-jDyKEvRpBOl8In4skDZ5-sJcZhmJGMwMVFyilYcNw_fHoS6xZdOUC4U_-n3Wx0',
    gallery: ['https://picsum.photos/seed/neon-drift-1/1920/1080', 'https://picsum.photos/seed/neon-drift-2/1920/1080'],
    isTrending: true,
  },
   {
    id: 'dungeon-crawler-x',
    title: 'Dungeon Crawler X',
    developer: 'Goblin Games',
    publisher: 'Goblin Games',
    releaseDate: 'Feb 14, 2024',
    price: '$19.99',
    description: 'Explore dark dungeons and find epic loot.',
    longDescription: 'Delve deep into procedurally generated dungeons, battling fierce monsters and uncovering powerful artifacts. With endless replayability, deep character progression, and challenging boss fights, Dungeon Crawler X is the ultimate test of your skills.',
    genres: ['RPG', 'Roguelike', 'Indie'],
    platforms: ['desktop_windows'],
    rating: 4.8,
    reviewCount: 5210,
    heroImage: 'https://picsum.photos/seed/dungeon-crawler-x-hero/1280/720',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPSBVP_sBoiPw5nKRuQg7B4ZdyaD9fFeTUZWQKnvSAq0DhRjp8fgzZe9nO9eWNmN02UJs_9IjO5FQKp1-CWERc_mwE0yVyMkM05dfbD8DWSC8Xr-pj5RAqVlLpvQ4yWLCS1qMLl_7wBCn6D-hsMil-IVmmLUryyKp81C9vMoP34UNrU65-LxgD3dzkmYxShzjk7mTr-oyQflAQGYEOQQNTDv0PnGWBBsijp_Jn6BrXhiPtAUek8GMvemEAmqnyEwXb89OQTBpKZyA',
    gallery: ['https://picsum.photos/seed/dungeon-crawler-x-1/1920/1080', 'https://picsum.photos/seed/dungeon-crawler-x-2/1920/1080'],
    isTrending: true,
  },
];

export const MOCK_USER: User = {
  username: 'AlexD_23',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9fR-4c6abafml980q_28mha0f9OYAxYEqIzbRPG7eLXOcygLuoW9RrkIdPHk5ULBAFYaFh9LSIhILQx4eUyBhtrhWQYYiJsnTylroaRol-McDDX69aShBEGOdFK6gqFZHDGH8_in2xiU2YgOxWmtfhHVaowO4rwOlzD4Ka9KlwdYFYy2rNUngq65q4qfDfThknOXGop05cY6E_oL53vR4fUYsLUV19Gsu5QUZHKdoPYPNMw2UBsDwiOGPiLOVpul4HFns8sLAh0g',
  memberSince: 'January 2023',
  bio: 'Explorer of digital worlds and champion of indie gems. Currently battling through the Forgotten Realms.',
  library: ['cyberpunk-odyssey', 'stellar-odyssey', 'forgotten-realms', 'neon-drift', 'dungeon-crawler-x'],
  wishlist: ['speed-demons-4', 'echoes-of-war'],
  reviews: [
    {
      id: 'review-1',
      gameId: 'forgotten-realms',
      user: {
        name: 'AlexD_23',
        avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC9fR-4c6abafml980q_28mha0f9OYAxYEqIzbRPG7eLXOcygLuoW9RrkIdPHk5ULBAFYaFh9LSIhILQx4eUyBhtrhWQYYiJsnTylroaRol-McDDX69aShBEGOdFK6gqFZHDGH8_in2xiU2YgOxWmtfhHVaowO4rwOlzD4Ka9KlwdYFYy2rNUngq65q4qfDfThknOXGop05cY6E_oL53vR4fUYsLUV19Gsu5QUZHKdoPYPNMw2UBsDwiOGPiLOVpul4HFns8sLAh0g',
      },
      rating: 5,
      comment: 'An absolute masterpiece. The world is breathtakingly detailed, and the story kept me hooked for over 100 hours. A must-play for any RPG fan.',
    },
  ],
};


export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    gameId: 'cyberpunk-odyssey',
    user: {
      name: 'Alex Johnson',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCyQ1ziVd6aX5MsegmuDvzVVBsDZXJlhxRdtaFDt3vPkTLhx6wCt7xsDDOcom2Rd7cG5F2uOuifdIWCjCcI9qGQp0pyXOjPtTAX404ngNHfIYHt5DvzUYlsEi28UHEvQvcznK5-3ghGwdVomZJUmBQ35FMmkSZ9OhwEaB6IWUMDTkMKrwdJvvQmiq-NoqNH13jiQiWu68rU7ZfIVqXSlsef0NVLSgVCyDYSrFnAeZDbJIrhOr04oShyt4Ikl9NRONuWZvCkHtJiems',
    },
    rating: 5,
    comment: "An absolute masterpiece. The world is breathtakingly detailed, and the story kept me hooked for over 100 hours. A must-play for any RPG fan.",
  },
  {
    id: 'r2',
    gameId: 'cyberpunk-odyssey',
    user: {
      name: 'Samantha Chen',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIUXvFLZz3gE3FKc0DMjlWYGDyjJrGiJ3G07PFLa-Bs8M87kIciWSm2NdjsmCJI9jo6cevYC66DDwnZo3LtfOScWqm2N2Oth7vTtgz0e6c3zQGYoJEdwrY0ppuKjBtIYRd0IABc7ig0uLDYHLODHXhgvWKkxnT232-oV-kmA5A0VBv_yIGTbWWIoSJdPLcPU89K5itwztbbCVjyzMDFIYYgYpoXKQAJjBFRUBqTiB6ZpMkMoU5WiyT5J72pAdltVsRQueMOtBi8_o',
    },
    rating: 4,
    comment: "Great game with a few technical hiccups on launch, but the patches have fixed most of them. The atmosphere is incredible. Worth the price.",
  },
  {
    id: 'r3',
    gameId: 'cyberpunk-odyssey',
    user: {
      name: 'Mike Rodriguez',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7stYy2ZKXcj1mSVJEk9_5tefXv4xd42V8WOu-eHjgnmPs7u1XEsptArmnFb-jbxvEOmtHQ5U5QKqVUyce_M5BMJlZKWIDSAhdZuNGN7YNg8PEZoTaK9W6LaZaksqD1zE8CGEZEGFc5VXhNPZ_kOa-PEUJ_Rk2Pve6XeHo48gAajysWhZtpB7xXOKMKLRr9E8ZnKtlOj38oRA9aeF2pmOQplmbXrm1ihYs2qoH3ZsrGNVSXgy49NtOWckV6hI_n181N_IocW8xt-c',
    },
    rating: 4.5,
    comment: "The gameplay is slick, the customization is deep, and Neo-Kyoto is a joy to explore. Combat feels responsive and impactful. Highly recommend.",
  },
];
